run:
  timeout: 5m
  tests: true
  build-tags:
    - integration

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - typecheck
    - unused
    - gosimple
    - gosec
    - dupl
    - goconst
    - gocyclo
    - misspell
    - unparam
    - nakedret
    - prealloc
    - bodyclose
    - rowserrcheck
    - stylecheck
    - shadow
    - copyloopvar

linters-settings:
  govet:
    enable:
      - shadow
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  goimports:
    local-prefixes: github.com/prism-php/prism-go

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - dupl
    - linters:
        - stylecheck
      text: "ST1000:"